Update selinux.yml

diff --git a/.github/workflows/selinux.yml b/.github/workflows/selinux.yml
--- a/.github/workflows/selinux.yml
+++ b/.github/workflows/selinux.yml
@@ -1,4 +1,4 @@
-name: Build ScamsungKernel Selinux
+name: Build OnyxKernel Selinux
 
 on:
   push:
@@ -46,9 +46,9 @@ jobs:
         BRANCH="${{ github.event.inputs.kernel_branch }}"
         
         if [ -z "$BRANCH" ]; then
-          git clone --depth=1 --recursive "$REPO" $GITHUB_WORKSPACE/kernel_src
+          git clone --depth=1 --recursive "$REPO" $GITHUB_WORKSPACE/blxyzz
         else
-          git clone --depth=1 -b "$BRANCH" --recursive "$REPO" $GITHUB_WORKSPACE/kernel_src
+          git clone --depth=1 -b "$BRANCH" --recursive "$REPO" $GITHUB_WORKSPACE/blxyzz
         fi
         mkdir -p $GITHUB_WORKSPACE/toolchains && cd $GITHUB_WORKSPACE/toolchains
         CHOSEN_CLANG="${{ github.event.inputs.clang_version || 'clang-10' }}"
@@ -67,9 +67,9 @@ jobs:
         export ARCH=arm64 SUBARCH=arm64 OUT_DIR=$GITHUB_WORKSPACE/out USE_CCACHE=1 CCACHE_DIR=~/.cache/ccache
         export GCC_64=aarch64-linux-android- GCC_32=arm-linux-androideabi-
         
-        ccache -M 5G && mkdir -p $OUT_DIR && cd $GITHUB_WORKSPACE/kernel_src
+        ccache -M 5G && mkdir -p $OUT_DIR && cd $GITHUB_WORKSPACE/blxyzz
         DEFCONFIG="${{ github.event.inputs.defconfig_name || 'vendor/a23_eur_open_defconfig' }}"
-        DEFCONFIG_PATH="$GITHUB_WORKSPACE/kernel_src/arch/arm64/configs/$DEFCONFIG"
+        DEFCONFIG_PATH="$GITHUB_WORKSPACE/blxyzz/arch/arm64/configs/$DEFCONFIG"
         SELINUX_CHOICE="${{ github.event.inputs.selinux_mode || 'permissive' }}"
         
         if [ "$SELINUX_CHOICE" = "permissive" ]; then
@@ -99,11 +99,11 @@ jobs:
       run: |
         rm -rf $GITHUB_WORKSPACE/zip_stage && mkdir -p $GITHUB_WORKSPACE/zip_stage
         
-        if [ -d "$GITHUB_WORKSPACE/ScamsungKernel" ]; then
-          cp -r $GITHUB_WORKSPACE/ScamsungKernel/* $GITHUB_WORKSPACE/zip_stage/
+        if [ -d "$GITHUB_WORKSPACE/AnyKernel3-A235f" ]; then
+          cp -r $GITHUB_WORKSPACE/AnyKernel3-A235f/* $GITHUB_WORKSPACE/zip_stage/
           find $GITHUB_WORKSPACE/zip_stage/ -name "*.zip" -type f -delete
         else
-          echo "ERROR: ScamsungKernel folder not found!" && exit 1
+          echo "ERROR: AnyKernel3-A235f folder not found!" && exit 1
         fi
         
         if [ -f "$GITHUB_WORKSPACE/out/arch/arm64/boot/Image" ]; then
@@ -114,10 +114,10 @@ jobs:
         
         [ -f "$GITHUB_WORKSPACE/out/arch/arm64/boot/dtbo.img" ] && cp $GITHUB_WORKSPACE/out/arch/arm64/boot/dtbo.img $GITHUB_WORKSPACE/zip_stage/dtbo.img
         
-        cd $GITHUB_WORKSPACE/zip_stage && zip -r9 $GITHUB_WORKSPACE/ScamsungKernel.zip ./*
+        cd $GITHUB_WORKSPACE/zip_stage && zip -r9 $GITHUB_WORKSPACE/AnyKernel3-A235f.zip ./*
         
         # Ambil versi kernel asli dan status SELinux
-        cd $GITHUB_WORKSPACE/kernel_src
+        cd $GITHUB_WORKSPACE/blxyzz
         KERNEL_VERSION=$(make kernelversion)
         SELINUX_MODE="${{ github.event.inputs.selinux_mode || 'permissive' }}"
         SELINUX_CAPITAL=$(echo "$SELINUX_MODE" | awk '{print toupper(substr($0,1,1))substr($0,2)}')
@@ -127,9 +127,9 @@ jobs:
     - name: Upload to GitHub Release
       uses: softprops/action-gh-release@v2
       with:
-        files: ScamsungKernel.zip
+        files: AnyKernel3-A235f.zip
         tag_name: "${{ env.RELEASE_TAG }}"
-        name: "Scamsung Kernel v${{ env.LINUX_VERSION }} [${{ env.SELINUX_STATUS }}]"
+        name: "Onyx Kernel v${{ env.LINUX_VERSION }} [${{ env.SELINUX_STATUS }}]"
         body: |
           ### Kernel Build Details
           - **Linux Version**: `v${{ env.LINUX_VERSION }}`
